language: node_js
node_js:
- 'node'
sudo: false

script: npm run ci:test

after_success:
  - npm install coveralls ocular.js
  - $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls
  - $(npm bin)/nyc report --reporter=clover
  - $(npm bin)/ocular coverage/clover.xml

cache:
  directories:
  - node_modules

before_cache:
  - rm -rf node_modules/.cache
